### ISSUE TITLE
Why doesn't this work

### ISSUE THREAD

**Issue by davilos** [meehawk/pokemon#1]
Hi man, i was testing this code, so i had a problem. In the pokemon_id variable, i changed `
pokemon_id = random.randint(900, 1000)` and run many times. But nothings appears in the README.MD.
I entered in this site: https://pokeapi.co/api/v2/pokemon
and the key's value (count) is 1154, this is the pokemons's number, right? Then, the limit would be 1154, or
i'm wrong?

**Comment by meehawk** [comment]
@davilos I think you are on point. Feels like there might be some unhandled error causing README to not be updated. I'll fix the code to indicate so. Sometimes the pokeapi fails in an unreliable fashion for some perfectly valid requests. Maybe there's an issue with error handling there
